name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: [main]

jobs:
  cabal:
    name: ${{ matrix.cfg.os }} / ghc ${{ matrix.cfg.ghc }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      matrix:
        cfg:
          - { os: ubuntu-latest  , ghc: "9.10.1"  }
          - { os: ubuntu-latest  , ghc: "9.8.2"  }
          - { os: ubuntu-latest  , ghc: "9.6.2"  }
          - { os: ubuntu-latest  , ghc: "9.4.7"  }
          - { os: ubuntu-latest  , ghc: "9.2.8"  }
          - { os: ubuntu-latest  , ghc: "9.0.2"  }
          - { os: ubuntu-latest  , ghc: "8.10.7" }
          - { os: ubuntu-latest  , ghc: "8.8.4"  }
          - { os: macOS-latest   , ghc: "9.10.1"  }
          - { os: windows-latest , ghc: "9.10.1"  }

    steps:
    - name: Checkout commit
      uses: actions/checkout@v3
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - name: Set up GHC & cabal
      uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.cfg.ghc }}
        cabal-version: ${{ matrix.cfg.cabal }}

    - name: Build ghc-tcplugin-api
      run: cabal build ghc-tcplugin-api

    - name: Build and lint System F example
      # Skip this test on GHC 8.8.4: we need StandaloneKindSignatures.
      if: matrix.cfg.ghc != '8.8.4'
      working-directory: ./examples/SystemF
      run: cabal build system-f
